- project:
    check:
      jobs:
        - "thoth-coala"
    gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
    post:
      jobs:
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "user-api"

    kebechet-auto-gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
